version: '2.1'
services:
  bucket-http-proxy:
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10M
    build:
      context: .
      dockerfile_inline: |
        FROM scratch
        COPY bucket-http-proxy /
        CMD [ "./bucket-http-proxy" ]
    environment:
      - BUCKET_REGION=us-east-1
      - BUCKET_NAME=repo-test
      - MODIFY_ALLOW_HEADER=X-USER
    network_mode: host
    volumes:
      # To make sure the CACerts are available, volume mount the pki directory:
      - "/etc/pki:/etc/pki:ro,z"

  nginx:
    restart: unless-stopped
    sysctls:
      - net.netfilter.nf_conntrack_tcp_timeout_time_wait=60
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc:
        soft: 10000
        hard: 10000
      nofile:
        soft: 999999
        hard: 999999
    logging:
      driver: json-file
      options:
        max-size: 10M
    image: nginx
    ports:
      - 80:80
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro,z"
      - "./logs:/etc/nginx/logs:rw,z"
    extra_hosts:
      - "host.docker.internal:host-gateway"

